services:
    scraper_service:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: scraper
        image: scraper
        working_dir: /scraper
        volumes:
            - ./scraper:/scraper
        tty: true
